Repository UruruLab/Ururu-Backend, pull requests merged in 2025-07, with the labels that each got.

#95 Product 삭제 Service 및 Controller 구현 및 해당 상품의 옵션 조회 Controller 구현
  build.gradle
  src/main/java/com/ururulab/ururu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/image/service/ImageService.java
  src/main/java/com/ururulab/ururu/product/controller/ProductController.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductRequest.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductOptionRepository.java
  src/main/java/com/ururulab/ururu/product/service/CategoryCacheService.java
  src/main/java/com/ururulab/ururu/product/service/ImageHashService.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionImageService.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionService.java
  src/main/java/com/ururulab/ururu/product/service/ProductService.java
  src/main/java/com/ururulab/ururu/product/service/validation/ProductValidator.java
Labels: 🔥 BE, 💫 Feature

#94 Member 도메인 기본 배송지, 선호도 Controller 구현
  src/main/java/com/ururulab/ururu/member/controller/BeautyProfileController.java
  src/main/java/com/ururulab/ururu/member/controller/MemberAgreementController.java
  src/main/java/com/ururulab/ururu/member/controller/MemberController.java
  src/main/java/com/ururulab/ururu/member/controller/MemberPreferenceController.java
  src/main/java/com/ururulab/ururu/member/controller/ShippingAddressController.java
  src/main/java/com/ururulab/ururu/member/domain/dto/request/MemberPreferenceRequest.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/BeautyProfileCreateResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/BeautyProfileGetResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/BeautyProfileUpdateResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/EmailAvailabilityResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/GetEmailAvailabilityResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/GetMyProfileResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/GetNicknameAvailabilityResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/MemberAgreementCreateResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/MemberGetResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/MemberPreferenceResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/MemberUpdateResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/NicknameAvailabilityResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/UpdateMemberResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/UpdateMyProfileResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/response/WithdrawalPreviewResponse.java
  src/main/java/com/ururulab/ururu/member/domain/dto/validation/MemberPreferenceValidationConstants.java
  src/main/java/com/ururulab/ururu/member/domain/dto/validation/MemberPreferenceValidationMessages.java
  src/main/java/com/ururulab/ururu/member/domain/repository/MemberPreferenceRepository.java
  src/main/java/com/ururulab/ururu/member/service/BeautyProfileService.java
  src/main/java/com/ururulab/ururu/member/service/MemberAgreementService.java
  src/main/java/com/ururulab/ururu/member/service/MemberPreferenceService.java
  src/main/java/com/ururulab/ururu/member/service/MemberService.java
  src/main/java/com/ururulab/ururu/member/service/ShippingAddressService.java
  src/main/java/com/ururulab/ururu/seller/domain/repository/SellerRepository.java
Labels: 🔥 BE, 💫 Feature

#106 새 도메인(ururu.shop) 전환을 위한 CORS 설정 업데이트
  src/main/java/com/ururulab/ururu/global/config/CorsConfig.java
Labels: 🔥 BE, 🌳 Environment

#103 GroupBuy 공동구매 등록 Service, Controller 구현
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyController.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/common/DiscountStageDto.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/request/GroupBuyImageRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/request/GroupBuyImageUploadRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/request/GroupBuyOptionRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/request/GroupBuyRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/request/GroupBuyStatusUpdateRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/request/GroupBuyThumbnailUploadRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/response/GroupBuyCreateResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/validation/GroupBuyValidationConstants.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/dto/validation/GroupBuyValidationMessages.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/dto/validation/GroupBuyValidationConstants.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuy.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuyImage.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuyOption.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuyStatistics.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyOptionRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyOptionService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyThumbnailService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyDiscountStageValidator.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyValidator.java
  src/main/java/com/ururulab/ururu/groupBuy/util/DiscountStageParser.java
  src/main/java/com/ururulab/ururu/order/domain/dto/response/CartItemResponse.java
  src/main/java/com/ururulab/ururu/order/domain/repository/OrderItemRepository.java
  src/main/java/com/ururulab/ururu/order/service/OrderCreationService.java
  src/main/java/com/ururulab/ururu/product/controller/ProductController.java
  src/main/java/com/ururulab/ururu/product/controller/dto/request/ProductImageUploadRequest.java
  src/main/java/com/ururulab/ururu/product/controller/dto/request/ProductNoticeRequest.java
  src/main/java/com/ururulab/ururu/product/controller/dto/request/ProductOptionRequest.java
  src/main/java/com/ururulab/ururu/product/controller/dto/request/ProductRequest.java
  src/main/java/com/ururulab/ururu/product/controller/dto/response/CategoryResponse.java
  src/main/java/com/ururulab/ururu/product/controller/dto/response/ProductListResponse.java
  src/main/java/com/ururulab/ururu/product/controller/dto/response/ProductNoticeResponse.java
  src/main/java/com/ururulab/ururu/product/controller/dto/response/ProductOptionResponse.java
  src/main/java/com/ururulab/ururu/product/controller/dto/response/ProductResponse.java
  src/main/java/com/ururulab/ururu/product/controller/dto/response/ProductTagResponse.java
  src/main/java/com/ururulab/ururu/product/controller/dto/validation/ProductValidationConstants.java
  src/main/java/com/ururulab/ururu/product/controller/dto/validation/ProductValidationMessages.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductNotice.java
  src/main/java/com/ururulab/ururu/product/event/ProductImageUploadEvent.java
  src/main/java/com/ururulab/ururu/product/service/CategoryManagementService.java
  src/main/java/com/ururulab/ururu/product/service/ProductCategoryService.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionImageService.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionService.java
  src/main/java/com/ururulab/ururu/product/service/ProductService.java
  src/main/java/com/ururulab/ururu/product/service/ProductTagService.java
  src/main/java/com/ururulab/ururu/product/service/validation/ProductValidator.java
Labels: 🔥 BE, 💫 Feature

#108 도메인 설정 환경변수화 및 CORS/JWT 쿠키 설정 개선
  src/main/java/com/ururulab/ururu/auth/jwt/JwtCookieHelper.java
  src/main/java/com/ururulab/ururu/global/config/CorsConfig.java
  src/test/java/com/ururulab/ururu/UruruApplicationTests.java
  src/test/java/com/ururulab/ururu/config/TestCorsConfig.java
  src/test/resources/application.yml
Labels: 🔥 BE, 🌳 Environment

#109 토스페이먼츠 연동 결제 API 구현 (결제 요청 → 승인 및 상태 동기화)
  build.gradle
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyOptionRepository.java
  src/main/java/com/ururulab/ururu/member/domain/repository/MemberRepository.java
  src/main/java/com/ururulab/ururu/order/controller/CartController.java
  src/main/java/com/ururulab/ururu/order/controller/OrderCreationController.java
  src/main/java/com/ururulab/ururu/order/dto/request/CartItemAddRequest.java
  src/main/java/com/ururulab/ururu/order/dto/request/CartItemQuantityChangeRequest.java
  src/main/java/com/ururulab/ururu/order/dto/request/CartOrderCreateRequest.java
  src/main/java/com/ururulab/ururu/order/dto/request/GroupBuyOrderCreateRequest.java
  src/main/java/com/ururulab/ururu/order/dto/request/OrderItemRequest.java
  src/main/java/com/ururulab/ururu/order/dto/response/CartItemAddResponse.java
  src/main/java/com/ururulab/ururu/order/dto/response/CartItemQuantityChangeResponse.java
  src/main/java/com/ururulab/ururu/order/dto/response/CartItemResponse.java
  src/main/java/com/ururulab/ururu/order/dto/response/CartResponse.java
  src/main/java/com/ururulab/ururu/order/dto/response/OrderCreateResponse.java
  src/main/java/com/ururulab/ururu/order/dto/response/OrderItemResponse.java
  src/main/java/com/ururulab/ururu/order/dto/validation/CartValidationConstants.java
  src/main/java/com/ururulab/ururu/order/dto/validation/CartValidationMessages.java
  src/main/java/com/ururulab/ururu/order/dto/validation/OrderValidationConstants.java
  src/main/java/com/ururulab/ururu/order/dto/validation/OrderValidationMessages.java
  src/main/java/com/ururulab/ururu/order/service/CartService.java
  src/main/java/com/ururulab/ururu/order/service/OrderCreationService.java
  src/main/java/com/ururulab/ururu/payment/controller/PaymentController.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/Payment.java
  src/main/java/com/ururulab/ururu/payment/domain/policy/PaymentPolicy.java
  src/main/java/com/ururulab/ururu/payment/domain/repository/PaymentRepository.java
  src/main/java/com/ururulab/ururu/payment/domain/repository/PointTransactionRepository.java
  src/main/java/com/ururulab/ururu/payment/dto/request/PaymentConfirmRequestDto.java
  src/main/java/com/ururulab/ururu/payment/dto/request/PaymentRequestDto.java
  src/main/java/com/ururulab/ururu/payment/dto/request/TossWebhookDataDto.java
  src/main/java/com/ururulab/ururu/payment/dto/request/TossWebhookDto.java
  src/main/java/com/ururulab/ururu/payment/dto/response/PaymentConfirmResponseDto.java
  src/main/java/com/ururulab/ururu/payment/dto/response/PaymentFailResponseDto.java
  src/main/java/com/ururulab/ururu/payment/dto/response/PaymentResponseDto.java
  src/main/java/com/ururulab/ururu/payment/dto/response/TossPaymentResponseDto.java
  src/main/java/com/ururulab/ururu/payment/dto/validation/PaymentValidationConstants.java
  src/main/java/com/ururulab/ururu/payment/dto/validation/PaymentValidationMessages.java
  src/main/java/com/ururulab/ururu/payment/service/PaymentService.java
  src/test/java/com/ururulab/ururu/payment/service/PaymentServiceTest.java
  src/test/resources/application.yml
Labels: 🔥 BE, 💫 Feature, 🛠️ Refactor

#118 상품 데이터 DB 삽입 구현
  src/main/java/com/ururulab/ururu/global/config/loader/ProductSampleDataLoader.java
  src/main/java/com/ururulab/ururu/global/config/loader/SellerSampleDataLoader.java
  src/main/resources/data/makeupBase.json
  src/main/resources/data/makeupEye.json
  src/main/resources/data/makeupLip.json
  src/main/resources/data/skincareCream.json
  src/main/resources/data/skincareSkin.json
  src/main/resources/data/suncareSuncream.json
  src/main/resources/sql/categoryData.sql
Labels: 🔥 BE, 💫 Feature

#121 ProductSampleDataLoader import 오류 수정
  docker/docker-compose-prod.yml
  src/main/java/com/ururulab/ururu/global/config/loader/ProductSampleDataLoader.java
Labels: 🐞 Bug

#116 포인트 잔액 및 내역 조회 API 구현
  src/main/java/com/ururulab/ururu/payment/controller/PaymentController.java
  src/main/java/com/ururulab/ururu/payment/controller/PointController.java
  src/main/java/com/ururulab/ururu/payment/domain/repository/PointTransactionRepository.java
  src/main/java/com/ururulab/ururu/payment/dto/response/MemberPointResponse.java
  src/main/java/com/ururulab/ururu/payment/dto/response/PointTransactionListResponse.java
  src/main/java/com/ururulab/ururu/payment/dto/response/PointTransactionResponse.java
  src/main/java/com/ururulab/ururu/payment/service/PointService.java
  src/test/java/com/ururulab/ururu/payment/service/PointServiceTest.java
Labels: 🔥 BE, 💫 Feature

#125 공동구매 조회 service 및 controller 구현
  build.gradle
  src/main/java/com/ururulab/ururu/UruruApplication.java
  src/main/java/com/ururulab/ururu/global/config/QueryDSLConfig.java
  src/main/java/com/ururulab/ururu/global/config/RedisConfig.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyController.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuy.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/enumerated/GroupBuySortOption.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyOptionRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyQueryRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/impl/GroupBuyQueryRepositoryImpl.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/request/GroupBuyStatusUpdateRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyCreatePageResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyDetailResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyImageInfoResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyListResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyOptionInfoResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/ProductInfoResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/scheduler/GroupBuyRankingScheduler.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyDetailService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyListService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyPriceService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyProductService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyRankingService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyStockService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/UpdateGroupBuyStatusService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyDiscountStageValidator.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyValidator.java
  src/main/java/com/ururulab/ururu/groupBuy/util/TimeCalculator.java
  src/main/java/com/ururulab/ururu/order/domain/repository/OrderItemRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductOptionRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductRepository.java
Labels: 🔥 BE, 💫 Feature

#131 AI 서비스 연동 인프라 구축 - 상품 추천 API 클라이언트 구현
  .gitignore
  build.gradle
  docker/docker-compose-prod.yml
  scripts/README.md
  scripts/test-rds-connection.sh
  src/main/java/com/ururulab/ururu/global/client/AiServiceClient.java
  src/main/java/com/ururulab/ururu/global/config/HttpClientConfig.java
  src/main/java/com/ururulab/ururu/global/config/RetryConfig.java
  src/main/java/com/ururulab/ururu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/resources/sql/categoryData.sql
  src/test/java/com/ururulab/ururu/UruruApplicationTests.java
  src/test/java/com/ururulab/ururu/config/TestAiServiceConfig.java
  src/test/resources/application-test.yml
Labels: 🔥 BE, 💫 Feature, 🌳 Environment

#140 Blue-Green 배포 자동화 스크립트 및 CI/CD 설정
  .github/workflows/ci-cd.yml
  docker/app/Dockerfile
  docker/docker-compose-prod.yml
  docker/nginx/healthcheck.sh
  docker/nginx/nginx.conf.template
  docker/nginx/rollback.sh
  docker/nginx/switch.sh
Labels: 💫 Feature, 🌳 Environment

#143 SSH 직접 연결 방식으로 환경변수 전달 문제 해결 및 healthcheck 개선
  .github/workflows/ci-cd.yml
  docker/Dockerfile
  docker/nginx/healthcheck.sh
  docker/nginx/switch.sh
Labels: 🐞 Bug, 🌳 Environment

#132 공동구매 종료 시 통계 계산 기능 및 closed 자동화 구현
  src/main/java/com/ururulab/ururu/global/config/AsyncConfig.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyController.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyStatisticsController.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuy.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuyOption.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyOptionRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyStatisticsRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/impl/GroupBuyQueryRepositoryImpl.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/common/StockCheckDto.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/projection/GroupBuyOptionBasicInfo.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/request/GroupBuyRequest.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyCreateResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyOptionInfoResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyStatisticsDetailResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyStatisticsResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/event/GroupBuysBatchClosedEvent.java
  src/main/java/com/ururulab/ururu/groupBuy/event/StockDepletedEvent.java
  src/main/java/com/ururulab/ururu/groupBuy/listener/StockDepletedEventListener.java
  src/main/java/com/ururulab/ururu/groupBuy/scheduler/GroupBuyBatchScheduler.java
  src/main/java/com/ururulab/ururu/groupBuy/scheduler/GroupBuyRankingScheduler.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyBatchCloseService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyDeleteService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyDetailService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyListService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyOptionService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyPriceService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyRankingService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyRealtimeCloseService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyStatisticsCalculatorService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyStatisticsService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyStockService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/UpdateGroupBuyStatusService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyValidator.java
  src/main/java/com/ururulab/ururu/image/service/ImageService.java
  src/main/java/com/ururulab/ururu/order/domain/repository/OrderItemRepository.java
  src/main/java/com/ururulab/ururu/payment/service/PaymentService.java
Labels: 🔥 BE, 💫 Feature

#148 토큰 보안 강화 및 인증 상태 조회 최적화
  src/main/java/com/ururulab/ururu/auth/annotation/RateLimit.java
  src/main/java/com/ururulab/ururu/auth/constants/AuthConstants.java
  src/main/java/com/ururulab/ururu/auth/controller/AuthController.java
  src/main/java/com/ururulab/ururu/auth/controller/SellerAuthController.java
  src/main/java/com/ururulab/ururu/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/ururulab/ururu/auth/interceptor/RateLimitInterceptor.java
  src/main/java/com/ururulab/ururu/auth/jwt/validator/JwtTokenValidator.java
  src/main/java/com/ururulab/ururu/auth/service/JwtRefreshService.java
  src/main/java/com/ururulab/ururu/auth/service/SecurityLoggingService.java
  src/main/java/com/ururulab/ururu/auth/service/SellerAuthService.java
  src/main/java/com/ururulab/ururu/auth/service/TokenValidator.java
  src/main/java/com/ururulab/ururu/auth/storage/RefreshTokenStorage.java
  src/main/java/com/ururulab/ururu/auth/util/AuthCookieHelper.java
  src/main/java/com/ururulab/ururu/auth/util/AuthResponseHelper.java
  src/main/java/com/ururulab/ururu/auth/util/TokenExtractor.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
Labels: 🐞 Bug, 🔥 BE, 🛠️ Refactor

#146 AI 기반 그룹바이 추천 시스템 및 Redis 캐싱 구현
  src/main/java/com/ururulab/ururu/ai/controller/GroupBuyRecommendationController.java
  src/main/java/com/ururulab/ururu/ai/dto/GroupBuyRecommendationRequest.java
  src/main/java/com/ururulab/ururu/ai/dto/GroupBuyRecommendationResponse.java
  src/main/java/com/ururulab/ururu/ai/service/GroupBuyRecommendationCacheService.java
  src/main/java/com/ururulab/ururu/ai/service/GroupBuyRecommendationService.java
  src/main/java/com/ururulab/ururu/ai/service/UruruAiService.java
  src/main/java/com/ururulab/ururu/global/config/AiServiceConfig.java
  src/main/java/com/ururulab/ururu/global/config/RedisConfig.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/test/java/com/ururulab/ururu/ai/service/GroupBuyRecommendationServiceMockTest.java
  src/test/java/com/ururulab/ururu/infrastructure/redis/RedisCachingTest.java
  src/test/java/com/ururulab/ururu/infrastructure/redis/RedisConnectionTest.java
  src/test/java/com/ururulab/ururu/infrastructure/redis/RedisIntegrationTest.java
  src/test/java/com/ururulab/ururu/infrastructure/redis/SimpleRedisTest.java
Labels: 🔥 BE, 💫 Feature

#149 공동구매 목록 조회 페이지네이션 및 키워드 검색 기능 추가
  build.gradle
  src/main/java/com/ururulab/ururu/global/config/RedisConfig.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyController.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyMainController.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuy.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyQueryRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/impl/GroupBuyQueryRepositoryImpl.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/common/CursorInfoDto.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyDetailResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyListResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuyPageResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyListService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyMainService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyRankingService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyValidator.java
  src/main/java/com/ururulab/ururu/groupBuy/util/DiscountStageParser.java
  src/main/java/com/ururulab/ururu/groupBuy/util/TimeCalculator.java
  src/main/java/com/ururulab/ururu/product/service/ProductService.java
Labels: 🔥 BE, 💫 Feature

#152 BeautyProfile 기반 AI 추천 시스템 완전 통합 구현
  src/main/java/com/ururulab/ururu/ai/config/AiRecommendationProperties.java
  src/main/java/com/ururulab/ururu/ai/controller/GroupBuyRecommendationController.java
  src/main/java/com/ururulab/ururu/ai/service/BeautyProfileConversionService.java
  src/main/java/com/ururulab/ururu/ai/service/GroupBuyRecommendationService.java
  src/main/java/com/ururulab/ururu/ai/service/UruruAiService.java
  src/main/java/com/ururulab/ururu/global/config/AiServiceConfig.java
Labels: 🔥 BE, 💫 Feature

#155 Access Token 만료 시간 수정
  src/main/java/com/ururulab/ururu/auth/jwt/JwtCookieHelper.java
  src/main/java/com/ururulab/ururu/auth/jwt/JwtTokenProvider.java
Labels: 🐞 Bug, 🔥 BE

#156 공동구매 조회 관련 판매자 전용 API 개발 및 카테고리, 태그 API 개발
  src/main/java/com/ururulab/ururu/global/domain/repository/TagCategoryRepository.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyController.java
  src/main/java/com/ururulab/ururu/groupBuy/controller/GroupBuyStatisticsController.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/response/GroupBuySellerListResponse.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyListService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuyProductService.java
  src/main/java/com/ururulab/ururu/groupBuy/service/GroupBuySellerListService.java
  src/main/java/com/ururulab/ururu/groupBuy/util/AuthUtils.java
  src/main/java/com/ururulab/ururu/product/controller/ProductMetadataController.java
  src/main/java/com/ururulab/ururu/product/dto/common/CategoryTreeDto.java
  src/main/java/com/ururulab/ururu/product/dto/common/TagDto.java
  src/main/java/com/ururulab/ururu/product/dto/response/ProductMetadataResponse.java
  src/main/java/com/ururulab/ururu/product/service/ProductMetadataService.java
Labels: 🔥 BE, 💫 Feature

#160 Fix/159 cors
  .github/workflows/ci-cd.yml
  src/main/java/com/ururulab/ururu/global/config/CorsConfig.java
Labels: 🐞 Bug, 🔥 BE

#151 BeautyProfileService, MemberAgreementService TestCode 작성
  src/main/java/com/ururulab/ururu/global/config/loader/ProductSampleDataLoader.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/member/controller/MemberController.java
  src/main/java/com/ururulab/ururu/member/dto/request/BeautyProfileRequest.java
  src/main/java/com/ururulab/ururu/member/dto/validation/BeautyProfileValidationConstants.java
  src/main/java/com/ururulab/ururu/member/dto/validation/BeautyProfileValidationMessages.java
  src/main/java/com/ururulab/ururu/member/service/BeautyProfileService.java
  src/main/java/com/ururulab/ururu/member/service/MemberAgreementService.java
  src/main/java/com/ururulab/ururu/member/service/MemberPreferenceService.java
  src/main/java/com/ururulab/ururu/member/service/MemberService.java
  src/main/java/com/ururulab/ururu/member/service/ShippingAddressService.java
  src/main/resources/sql/categoryData-h2.sql
  src/main/resources/sql/categoryData-mysql.sql
  src/main/resources/sql/tagCategory-h2.sql
  src/main/resources/sql/tagCategory-mysql.sql
  src/main/resources/sql/tagData-h2.sql
  src/main/resources/sql/tagData-mysql.sql
  src/test/java/com/ururulab/ururu/member/service/BeautyProfileServiceTest.java
  src/test/java/com/ururulab/ururu/member/service/BeautyProfileTestFixture.java
  src/test/java/com/ururulab/ururu/member/service/MemberAgreementServiceTest.java
  src/test/java/com/ururulab/ururu/member/service/MemberAgreementTestFixture.java
  src/test/java/com/ururulab/ururu/member/service/MemberServiceTest.java
Labels: 🔥 BE, ✅ Test

#165 AuthTestFixture 및 기본 구조 구축
  src/test/java/com/ururulab/ururu/auth/AuthTestFixture.java
  src/test/java/com/ururulab/ururu/auth/AuthTestFixtureTest.java
  src/test/java/com/ururulab/ururu/auth/service/AuthServiceTestBase.java
Labels: 🔥 BE, ✅ Test

#169 Auth Service 계층 테스트 코드 작성
  src/test/java/com/ururulab/ururu/auth/AuthTestFixtureTest.java
  src/test/java/com/ururulab/ururu/auth/AuthTestHelper.java
  src/test/java/com/ururulab/ururu/auth/service/AuthServiceTestBase.java
  src/test/java/com/ururulab/ururu/auth/service/SellerAuthServiceTest.java
  src/test/java/com/ururulab/ururu/auth/service/SocialLoginServiceFactoryTest.java
  src/test/java/com/ururulab/ururu/auth/service/TokenValidatorTest.java
  src/test/java/com/ururulab/ururu/auth/service/social/GoogleLoginServiceTest.java
  src/test/java/com/ururulab/ururu/auth/service/social/KakaoLoginServiceTest.java
Labels: 🔥 BE, ✅ Test

#177 Grafana와 Prometheus 모니터링 시스템 구축
  .github/workflows/ci-cd.yml
  .github/workflows/deploy-monitoring.yml
  build.gradle
  docker/docker-compose-monitoring.yml
  docker/monitoring/grafana/provisioning/dashboards/dashboards.yml
  docker/monitoring/grafana/provisioning/datasources/datasources.yml
  docker/monitoring/prometheus/prometheus.yml
  src/main/java/com/ururulab/ururu/global/config/MetricsConfig.java
  src/main/java/com/ururulab/ururu/global/config/SecurityConfig.java
  src/main/java/com/ururulab/ururu/global/controller/MonitoringTestController.java
Labels: 🔥 BE, 💫 Feature, 🌳 Environment

#187 회원 탈퇴 로직 수정
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/member/service/MemberService.java
Labels: 🔥 BE, 💫 Feature

#191 로그인 실패 시 예외 대신 프론트엔트 리다이렉트로 처리
  src/main/java/com/ururulab/ururu/auth/controller/AuthController.java
  src/main/java/com/ururulab/ururu/member/service/MemberService.java
Labels: 🐞 Bug, 🔥 BE

#197 메인홈 랭킹 API 인증 없이 접근 가능 코드 추가
  src/main/java/com/ururulab/ururu/global/config/SecurityConfig.java
Labels: 🐞 Bug, 🔥 BE

#202 공동구매 최소 수량 검증 수정
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/groupBuy/dto/validation/GroupBuyValidationConstants.java
  src/main/java/com/ururulab/ururu/groupBuy/service/validation/GroupBuyDiscountStageValidator.java
Labels: 🐞 Bug, 🔥 BE

#205 주문서 API 응답 개선 및 예외 처리 보완
  src/main/java/com/ururulab/ururu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ururulab/ururu/order/dto/response/OrderItemResponse.java
  src/main/java/com/ururulab/ururu/order/service/CartService.java
  src/main/java/com/ururulab/ururu/order/service/OrderCreationService.java
Labels: 🔥 BE, 💫 Feature

#208 공동구매 상세 조회 경로 권한 허용
  src/main/java/com/ururulab/ururu/global/config/SecurityConfig.java
Labels: 🐞 Bug, 🔥 BE

#210 PayMethod enum 구조 개선 및 EASY_PAY 통합
  src/main/java/com/ururulab/ururu/payment/domain/entity/enumerated/PayMethod.java
Labels: 🔥 BE, 💫 Feature

#216 장바구니 일괄 아이템 추가 기능 구현
  src/main/java/com/ururulab/ururu/order/controller/CartController.java
Labels: 🔥 BE, 💫 Feature
