Repository UruruLab/Ururu-Backend, pull requests merged in 2025-06, with the labels that each got.

#4 feat: application, dev, prod 설정파일 yml 추가
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🌳 Environment

#11 feat: application-dev.yml ignore 처리
  .gitignore
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🌳 Environment

#7 feat: ProductEntity 생성
  src/main/java/com/ururulab/ururu/domain/product/model/entity/Product.java
  src/main/java/com/ururulab/ururu/domain/product/model/entity/enumerated/Status.java
  src/main/java/com/ururulab/ururu/global/common/entity/BaseEntity.java
Labels: 🔥 BE, 💫 Feature

#12 feat: ProductOption, ProductNotice Entity 생성
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductNotice.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductOption.java
  src/main/java/com/ururulab/ururu/product/domain/entity/enumerated/Status.java
Labels: 🔥 BE, 💫 Feature

#14 feat: 로그인 관련 의존성 추가 및 User 도메인 모델 구현
  build.gradle
  src/main/java/com/ururulab/ururu/global/config/SecurityConfig.java
  src/main/java/com/ururulab/ururu/user/domain/entity/BeautyProfile.java
  src/main/java/com/ururulab/ururu/user/domain/entity/ShippingAddress.java
  src/main/java/com/ururulab/ururu/user/domain/entity/User.java
  src/main/java/com/ururulab/ururu/user/domain/entity/UserAgreement.java
  src/main/java/com/ururulab/ururu/user/domain/entity/UserPreference.java
  src/main/java/com/ururulab/ururu/user/domain/entity/enumerated/AgreementType.java
  src/main/java/com/ururulab/ururu/user/domain/entity/enumerated/Gender.java
  src/main/java/com/ururulab/ururu/user/domain/entity/enumerated/PurchaseFrequency.java
  src/main/java/com/ururulab/ururu/user/domain/entity/enumerated/Role.java
  src/main/java/com/ururulab/ururu/user/domain/entity/enumerated/SkinType.java
  src/main/java/com/ururulab/ururu/user/domain/entity/enumerated/SocialProvider.java
Labels: 🔥 BE, 💫 Feature

#17 SecurityConfig header설정 추가 - h2콘솔 문제 해결
  src/main/java/com/ururulab/ururu/global/config/SecurityConfig.java
Labels: 🔥 BE, 🌳 Environment

#20 Category, Productcategory Entity 생성
  src/main/java/com/ururulab/ururu/product/domain/entity/Category.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductCategory.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductOption.java
  src/main/resources/sql/categoryData.sql
Labels: 🔥 BE, 💫 Feature

#23 JWT 토큰 처리 및 카카오 OAuth 기본 설정 구현
  src/main/java/com/ururulab/ururu/global/auth/dto/JwtTokenResponse.java
  src/main/java/com/ururulab/ururu/global/auth/dto/KakaoOAuthRequest.java
  src/main/java/com/ururulab/ururu/global/auth/dto/OAuthUserInfo.java
  src/main/java/com/ururulab/ururu/global/auth/jwt/JwtProperties.java
  src/main/java/com/ururulab/ururu/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/ururulab/ururu/global/auth/oauth/KakaoOAuthProperties.java
Labels: 🔥 BE, 💫 Feature

#31 리뷰 도메인 핵심 검증 로직 및 ReviewRequest 1차 입력 검증 구현
  src/main/java/com/ururulab/ururu/global/common/entity/enumerated/EnumParser.java
  src/main/java/com/ururulab/ururu/global/common/entity/enumerated/Gender.java
  src/main/java/com/ururulab/ururu/global/common/entity/enumerated/SkinType.java
  src/main/java/com/ururulab/ururu/global/common/repository/TagRepository.java
  src/main/java/com/ururulab/ururu/global/controller/Controller.java
  src/main/java/com/ururulab/ururu/global/validation/EnumValue.java
  src/main/java/com/ururulab/ururu/global/validation/EnumValueValidator.java
  src/main/java/com/ururulab/ururu/global/validation/ValidationMessages.java
  src/main/java/com/ururulab/ururu/review/controller/ReviewController.java
  src/main/java/com/ururulab/ururu/review/domain/dto/request/ReviewRequest.java
  src/main/java/com/ururulab/ururu/review/domain/dto/validation/ValidationConstants.java
  src/main/java/com/ururulab/ururu/review/domain/dto/validation/ValidationMessages.java
  src/main/java/com/ururulab/ururu/review/domain/dto/validation/ValidationPatterns.java
  src/main/java/com/ururulab/ururu/review/domain/entity/Review.java
  src/main/java/com/ururulab/ururu/review/domain/entity/ReviewTag.java
  src/main/java/com/ururulab/ururu/review/domain/entity/enumerated/AgeGroup.java
  src/main/java/com/ururulab/ururu/review/domain/policy/ReviewImagePolicy.java
  src/main/java/com/ururulab/ururu/review/domain/policy/ReviewPolicy.java
  src/main/java/com/ururulab/ururu/review/domain/repository/ReviewRepository.java
  src/main/java/com/ururulab/ururu/review/service/ReviewImageService.java
  src/main/java/com/ururulab/ururu/review/service/ReviewService.java
Labels: 🔥 BE, 💫 Feature

#27 Review 관련 도메인 설계
  src/main/java/com/ururulab/ururu/global/common/entity/Tag.java
  src/main/java/com/ururulab/ururu/global/common/entity/TagCategory.java
  src/main/java/com/ururulab/ururu/global/common/entity/enumerated/EnumParser.java
  src/main/java/com/ururulab/ururu/global/common/entity/enumerated/Gender.java
  src/main/java/com/ururulab/ururu/global/common/entity/enumerated/SkinType.java
  src/main/java/com/ururulab/ururu/global/common/repository/TagRepository.java
  src/main/java/com/ururulab/ururu/global/controller/Controller.java
  src/main/java/com/ururulab/ururu/global/validation/EnumValue.java
  src/main/java/com/ururulab/ururu/global/validation/EnumValueValidator.java
  src/main/java/com/ururulab/ururu/global/validation/ValidationMessages.java
  src/main/java/com/ururulab/ururu/member/domain/entity/BeautyProfile.java
  src/main/java/com/ururulab/ururu/member/domain/entity/Member.java
  src/main/java/com/ururulab/ururu/member/domain/entity/enumerated/Gender.java
  src/main/java/com/ururulab/ururu/member/domain/entity/enumerated/SkinType.java
  src/main/java/com/ururulab/ururu/review/controller/ReviewController.java
  src/main/java/com/ururulab/ururu/review/domain/dto/request/ReviewRequest.java
  src/main/java/com/ururulab/ururu/review/domain/dto/validation/ValidationConstants.java
  src/main/java/com/ururulab/ururu/review/domain/dto/validation/ValidationMessages.java
  src/main/java/com/ururulab/ururu/review/domain/dto/validation/ValidationPatterns.java
  src/main/java/com/ururulab/ururu/review/domain/entity/Review.java
  src/main/java/com/ururulab/ururu/review/domain/entity/ReviewImage.java
  src/main/java/com/ururulab/ururu/review/domain/entity/ReviewLike.java
  src/main/java/com/ururulab/ururu/review/domain/entity/ReviewSummary.java
  src/main/java/com/ururulab/ururu/review/domain/entity/ReviewTag.java
  src/main/java/com/ururulab/ururu/review/domain/entity/enumerated/AgeGroup.java
  src/main/java/com/ururulab/ururu/review/domain/policy/ReviewImagePolicy.java
  src/main/java/com/ururulab/ururu/review/domain/policy/ReviewPolicy.java
  src/main/java/com/ururulab/ururu/review/domain/repository/ReviewRepository.java
  src/main/java/com/ururulab/ururu/review/service/ReviewImageService.java
  src/main/java/com/ururulab/ururu/review/service/ReviewService.java
Labels: 🔥 BE, 🌳 Environment

#32 소셜 로그인 공통 구조 및 추상화 레이어 구현
  src/main/java/com/ururulab/ururu/global/auth/dto/info/OAuthUserInfo.java
  src/main/java/com/ururulab/ururu/global/auth/dto/info/SocialMemberInfo.java
  src/main/java/com/ururulab/ururu/global/auth/dto/request/KakaoOAuthRequest.java
  src/main/java/com/ururulab/ururu/global/auth/dto/request/SocialLoginRequest.java
  src/main/java/com/ururulab/ururu/global/auth/dto/response/JwtTokenResponse.java
  src/main/java/com/ururulab/ururu/global/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/ururulab/ururu/global/auth/exception/SocialLoginException.java
  src/main/java/com/ururulab/ururu/global/auth/exception/SocialMemberInfoException.java
  src/main/java/com/ururulab/ururu/global/auth/exception/SocialTokenExchangeException.java
  src/main/java/com/ururulab/ururu/global/auth/exception/UnsupportedSocialProviderException.java
  src/main/java/com/ururulab/ururu/global/auth/service/SocialLoginService.java
  src/main/java/com/ururulab/ururu/global/auth/service/SocialLoginServiceFactory.java
  src/main/java/com/ururulab/ururu/global/common/dto/ApiResponse.java
  src/main/java/com/ururulab/ururu/global/exception/GlobalExceptionHandler.java
Labels: 🔥 BE, 💫 Feature

#33 Product, ProductOption, ProductNotice Entity 수정
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductNotice.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductOption.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductRepository.java
Labels: 🔥 BE, 🌳 Environment

#38 장바구니/주문 관련 도메인 설계
  src/main/java/com/ururulab/ururu/order/domain/entity/Cart.java
  src/main/java/com/ururulab/ururu/order/domain/entity/CartItem.java
  src/main/java/com/ururulab/ururu/order/domain/entity/Order.java
  src/main/java/com/ururulab/ururu/order/domain/entity/OrderHistory.java
  src/main/java/com/ururulab/ururu/order/domain/entity/OrderItem.java
  src/main/java/com/ururulab/ururu/order/domain/entity/enumerated/OrderStatus.java
  src/main/java/com/ururulab/ururu/order/domain/entity/enumerated/PaymentStatus.java
Labels: 🔥 BE, 💫 Feature

#39 Product 관련 DTO 구현, 검증 상수 클래스 생성 및 관련 Service 클래스 생성
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductNoticeRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductOptionRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/CategoryResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductNoticeResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductOptionResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/validation/ProductValidationConstants.java
  src/main/java/com/ururulab/ururu/product/domain/dto/validation/ProductValidationMessages.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductNotice.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionImageService.java
  src/main/java/com/ururulab/ururu/product/service/ProductService.java
Labels: 🔥 BE, 💫 Feature

#50 결제/포인트 관련 도메인 설계
  src/main/java/com/ururulab/ururu/payment/domain/entity/Payment.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/PointTransaction.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/Refund.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/enumerated/PayMethod.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/enumerated/PaymentStatus.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/enumerated/PointSource.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/enumerated/PointType.java
  src/main/java/com/ururulab/ururu/payment/domain/entity/enumerated/RefundStatus.java
  src/main/java/com/ururulab/ururu/payment/domain/policy/PaymentPolicy.java
  src/main/java/com/ururulab/ururu/payment/domain/policy/PointTransactionPolicy.java
  src/main/java/com/ururulab/ururu/payment/domain/policy/RefundPolicy.java
Labels: 🔥 BE, 💫 Feature

#58 Order 도메인 리팩터링 및 Payment 분리
  src/main/java/com/ururulab/ururu/order/domain/entity/Cart.java
  src/main/java/com/ururulab/ururu/order/domain/entity/CartItem.java
  src/main/java/com/ururulab/ururu/order/domain/entity/Order.java
  src/main/java/com/ururulab/ururu/order/domain/entity/OrderHistory.java
  src/main/java/com/ururulab/ururu/order/domain/entity/OrderItem.java
  src/main/java/com/ururulab/ururu/order/domain/entity/enumerated/PaymentStatus.java
  src/main/java/com/ururulab/ururu/order/domain/policy/CartItemPolicy.java
  src/main/java/com/ururulab/ururu/order/domain/policy/CartPolicy.java
  src/main/java/com/ururulab/ururu/order/domain/policy/OrderHistoryPolicy.java
  src/main/java/com/ururulab/ururu/order/domain/policy/OrderItemPolicy.java
  src/main/java/com/ururulab/ururu/order/domain/policy/OrderPolicy.java
Labels: 🔥 BE, 🛠️ Refactor

#61 ImageService 구현 및 Review 이미지 업로드 기능 통합
  build.gradle
  src/main/java/com/ururulab/ururu/UruruApplication.java
  src/main/java/com/ururulab/ururu/global/common/entity/Tag.java
  src/main/java/com/ururulab/ururu/global/config/AsyncConfig.java
  src/main/java/com/ururulab/ururu/global/config/S3Config.java
  src/main/java/com/ururulab/ururu/image/domain/ImageCategory.java
  src/main/java/com/ururulab/ururu/image/domain/ImageFormat.java
  src/main/java/com/ururulab/ururu/image/exception/InvalidImageFormatException.java
  src/main/java/com/ururulab/ururu/image/service/ImageService.java
  src/main/java/com/ururulab/ururu/review/controller/ReviewController.java
  src/main/java/com/ururulab/ururu/review/domain/dto/request/ImageUploadRequest.java
  src/main/java/com/ururulab/ururu/review/domain/dto/request/ReviewRequest.java
  src/main/java/com/ururulab/ururu/review/domain/entity/Review.java
  src/main/java/com/ururulab/ururu/review/domain/entity/ReviewImage.java
  src/main/java/com/ururulab/ururu/review/event/ReviewCreatedEvent.java
  src/main/java/com/ururulab/ururu/review/listener/ReviewImageListener.java
  src/main/java/com/ururulab/ururu/review/service/ReviewImageService.java
  src/main/java/com/ururulab/ururu/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: 🔥 BE, 💫 Feature

#56 WebClient를 RestClient로 전환하여 OAuth 소셜 로그인 개선
  build.gradle
  src/main/java/com/ururulab/ururu/auth/service/social/KakaoLoginService.java
  src/main/java/com/ururulab/ururu/global/config/HttpClientConfig.java
Labels: 🔥 BE, 🛠️ Refactor

#64 Seller 도메인 전체 구조 구현
  src/main/java/com/ururulab/ururu/order/domain/entity/Order.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/request/SellerRequest.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/response/SellerAvailabilityResponse.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/response/SellerResponse.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/validation/SellerValidationConstants.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/validation/SellerValidationMessages.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/validation/SellerValidationPatterns.java
  src/main/java/com/ururulab/ururu/seller/domain/entity/Seller.java
  src/main/java/com/ururulab/ururu/seller/domain/policy/SellerPolicy.java
  src/main/java/com/ururulab/ururu/seller/domain/repository/SellerRepository.java
Labels: 🔥 BE, 💫 Feature

#74 Google OAuth 소셜 로그인 기능 구현
  src/main/java/com/ururulab/ururu/auth/controller/AuthController.java
  src/main/java/com/ururulab/ururu/auth/controller/JwtRefreshController.java
  src/main/java/com/ururulab/ururu/auth/dto/info/GoogleUserInfo.java
  src/main/java/com/ururulab/ururu/auth/dto/info/SocialMemberInfo.java
  src/main/java/com/ururulab/ururu/auth/dto/response/GoogleTokenResponse.java
  src/main/java/com/ururulab/ururu/auth/oauth/GoogleOAuthProperties.java
  src/main/java/com/ururulab/ururu/auth/service/JwtRefreshService.java
  src/main/java/com/ururulab/ururu/auth/service/social/GoogleLoginService.java
Labels: 🔥 BE, 💫 Feature, 🛠️ Refactor

#71 장바구니 CRUD API 구현
  src/main/java/com/ururulab/ururu/groupBuy/domain/repository/GroupBuyOptionRepository.java
  src/main/java/com/ururulab/ururu/order/controller/CartController.java
  src/main/java/com/ururulab/ururu/order/domain/dto/request/CartItemAddRequest.java
  src/main/java/com/ururulab/ururu/order/domain/dto/request/CartItemQuantityChangeRequest.java
  src/main/java/com/ururulab/ururu/order/domain/dto/response/CartItemAddResponse.java
  src/main/java/com/ururulab/ururu/order/domain/dto/response/CartItemQuantityChangeResponse.java
  src/main/java/com/ururulab/ururu/order/domain/dto/response/CartItemResponse.java
  src/main/java/com/ururulab/ururu/order/domain/dto/response/CartResponse.java
  src/main/java/com/ururulab/ururu/order/domain/dto/validation/ValidationConstants.java
  src/main/java/com/ururulab/ururu/order/domain/dto/validation/ValidationMessages.java
  src/main/java/com/ururulab/ururu/order/domain/entity/Cart.java
  src/main/java/com/ururulab/ururu/order/domain/entity/CartItem.java
  src/main/java/com/ururulab/ururu/order/domain/entity/OrderHistory.java
  src/main/java/com/ururulab/ururu/order/domain/entity/OrderItem.java
  src/main/java/com/ururulab/ururu/order/domain/repository/CartItemRepository.java
  src/main/java/com/ururulab/ururu/order/domain/repository/CartRepository.java
  src/main/java/com/ururulab/ururu/order/domain/repository/OrderItemRepository.java
  src/main/java/com/ururulab/ururu/order/service/CartService.java
Labels: 🔥 BE, 💫 Feature

#70 Product Controller 및 Service 구현
  src/main/java/com/ururulab/ururu/global/common/repository/TagCategoryRepository.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuy.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuyImage.java
  src/main/java/com/ururulab/ururu/groupBuy/domain/entity/GroupBuyOption.java
  src/main/java/com/ururulab/ururu/product/controller/ProductController.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductImageUploadRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductOptionRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/CategoryResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductListResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductNoticeResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductOptionResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/response/ProductTagResponse.java
  src/main/java/com/ururulab/ururu/product/domain/dto/validation/ProductValidationMessages.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Category.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductCategory.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductNotice.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductOption.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductTag.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductCategoryRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductTagRepository.java
  src/main/java/com/ururulab/ururu/product/event/ProductImageUploadEvent.java
  src/main/java/com/ururulab/ururu/product/listner/ProductImageListener.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionImageService.java
  src/main/java/com/ururulab/ururu/product/service/ProductService.java
  src/main/java/com/ururulab/ururu/product/service/validation/ProductValidator.java
  src/main/resources/sql/categoryData.sql
  src/main/resources/sql/tagCategory.sql
  src/main/resources/sql/tagData.sql
Labels: 🔥 BE, 💫 Feature

#75 판매자 회원가입 기능 구현 및 검증 로직 개선
  src/main/java/com/ururulab/ururu/global/common/util/MaskingUtils.java
  src/main/java/com/ururulab/ururu/global/config/SecurityConfig.java
  src/main/java/com/ururulab/ururu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ururulab/ururu/seller/controller/SellerController.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/request/SellerSignupRequest.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/response/SellerSignupResponse.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/validation/SellerValidationMessages.java
  src/main/java/com/ururulab/ururu/seller/domain/dto/validation/SellerValidationPatterns.java
  src/main/java/com/ururulab/ururu/seller/domain/entity/Seller.java
  src/main/java/com/ururulab/ururu/seller/domain/policy/SellerPolicy.java
  src/main/java/com/ururulab/ururu/seller/service/SellerService.java
Labels: 🔥 BE, 💫 Feature

#86 BaseEntity를 JPA Auditing 방식으로 변경
  src/main/java/com/ururulab/ururu/UruruApplication.java
  src/main/java/com/ururulab/ururu/global/config/JpaAuditingConfig.java
  src/main/java/com/ururulab/ururu/global/domain/entity/BaseEntity.java
Labels: 🔥 BE, 🛠️ Refactor

#82 RestClient 네트워크 안정성 설정 및 소셜 로그인 서비스 리팩토링
  src/main/java/com/ururulab/ururu/auth/oauth/KakaoOAuthProperties.java
  src/main/java/com/ururulab/ururu/auth/service/social/AbstractSocialLoginService.java
  src/main/java/com/ururulab/ururu/auth/service/social/GoogleLoginService.java
  src/main/java/com/ururulab/ururu/auth/service/social/KakaoLoginService.java
  src/main/java/com/ururulab/ururu/auth/service/social/MemberTransactionService.java
  src/main/java/com/ururulab/ururu/global/config/CorsConfig.java
  src/main/java/com/ururulab/ururu/global/config/HttpClientConfig.java
Labels: 🔥 BE, 💫 Feature, 🛠️ Refactor

#84 Product 상품 상세 조회, 상품 수정 Service 및 Controller 구현
  src/main/java/com/ururulab/ururu/UruruApplication.java
  src/main/java/com/ururulab/ururu/global/config/AsyncConfig.java
  src/main/java/com/ururulab/ururu/global/domain/entity/TagCategory.java
  src/main/java/com/ururulab/ururu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ururulab/ururu/global/exception/error/ErrorCode.java
  src/main/java/com/ururulab/ururu/image/service/ImageService.java
  src/main/java/com/ururulab/ururu/product/controller/ProductController.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductImageUploadRequest.java
  src/main/java/com/ururulab/ururu/product/domain/dto/request/ProductRequest.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Category.java
  src/main/java/com/ururulab/ururu/product/domain/entity/Product.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductNotice.java
  src/main/java/com/ururulab/ururu/product/domain/entity/ProductOption.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductCategoryRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductOptionRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductRepository.java
  src/main/java/com/ururulab/ururu/product/domain/repository/ProductTagRepository.java
  src/main/java/com/ururulab/ururu/product/event/ProductImageDeleteEvent.java
  src/main/java/com/ururulab/ururu/product/listener/ProductImageDeleteListener.java
  src/main/java/com/ururulab/ururu/product/listener/ProductImageListener.java
  src/main/java/com/ururulab/ururu/product/service/CategoryManagementService.java
  src/main/java/com/ururulab/ururu/product/service/ImageHashService.java
  src/main/java/com/ururulab/ururu/product/service/ProductCategoryService.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionImageService.java
  src/main/java/com/ururulab/ururu/product/service/ProductOptionService.java
  src/main/java/com/ururulab/ururu/product/service/ProductService.java
  src/main/java/com/ururulab/ururu/product/service/ProductTagService.java
  src/main/java/com/ururulab/ururu/product/service/validation/ProductValidator.java
  src/main/java/com/ururulab/ururu/review/service/ReviewService.java
Labels: 🔥 BE, 💫 Feature
